  create table advertisement (
        id bigint generated by default as identity unique,
        other varchar(255),
        description varchar(2000) not null,
        remuneration varchar(255) not null,
        settlement_id bigint,
        category_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table jobcategory (
        id bigint generated by default as identity unique,
        main boolean not null,
        name varchar(255),
        main_id bigint,
        primary key (id)
    );

    create table settlement (
        id bigint generated by default as identity unique,
        settlement varchar(255),
        zip integer,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity unique,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    create table valueset (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table valuesetentry (
        id bigint generated by default as identity unique,
        bkey varchar(255) not null,
        valueSet_id bigint not null,
        primary key (id)
    );

    create table valuestore (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        value varchar(255) not null,
        primary key (id)
    );

    alter table advertisement 
        add constraint FKF85DD20564DDF1F3 
        foreign key (user_id) 
        references user;

    alter table advertisement 
        add constraint FKF85DD2055F105C76 
        foreign key (category_id) 
        references jobcategory;

    alter table advertisement 
        add constraint FKF85DD20582240ED3 
        foreign key (settlement_id) 
        references settlement;

    alter table jobcategory 
        add constraint FK57BF4BBB34F015DB 
        foreign key (main_id) 
        references jobcategory;

    alter table valuesetentry 
        add constraint FK247249C164F6DFF3 
        foreign key (valueSet_id) 
        references valueset;
        
        
insert into User (id, username, password) values (1, 'aacs', 'aacs');