    create table advertisement (
        id bigint generated by default as identity unique,
        other varchar(255),
        description varchar(2000) not null,
        homeJob boolean not null,
        maxOffer integer not null check (maxOffer>=1),
        remuneration varchar(255) not null,
        settlement_id bigint,
        category_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table help (
        id bigint generated by default as identity unique,
        category varchar(255) not null,
        message varchar(255) not null,
        subject varchar(255) not null,
        user_id bigint,
        primary key (id)
    );

    create table jobcategory (
        id bigint generated by default as identity unique,
        main boolean not null,
        name varchar(255),
        main_id bigint,
        primary key (id)
    );

    create table settlement (
        id bigint generated by default as identity unique,
        settlement varchar(255),
        zip integer,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity unique,
        other varchar(255),
        firstLogin boolean not null,
        lastLogin timestamp,
        password varchar(255) not null,
        registrationDate timestamp,
        username varchar(255) not null,
        settlement_id bigint,
        primary key (id)
    );

    create table user_advertisement (
        user_id bigint not null,
        savedAds_id bigint not null,
        primary key (user_id, savedAds_id),
        unique (savedAds_id)
    );

    create table valueset (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table valuesetentry (
        id bigint generated by default as identity unique,
        bkey varchar(255) not null,
        valueSet_id bigint not null,
        primary key (id)
    );

    create table valuestore (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        value varchar(255) not null,
        primary key (id)
    );

    alter table advertisement 
        add constraint FKF85DD20564DDF1F3 
        foreign key (user_id) 
        references user;

    alter table advertisement 
        add constraint FKF85DD2055F105C76 
        foreign key (category_id) 
        references jobcategory;

    alter table advertisement 
        add constraint FKF85DD20582240ED3 
        foreign key (settlement_id) 
        references settlement;

    alter table help 
        add constraint FK30CF4164DDF1F3 
        foreign key (user_id) 
        references user;

    alter table jobcategory 
        add constraint FK57BF4BBB34F015DB 
        foreign key (main_id) 
        references jobcategory;

    alter table user 
        add constraint FK36EBCB82240ED3 
        foreign key (settlement_id) 
        references settlement;

    alter table user_advertisement 
        add constraint FKDEE89091FFCC4F35 
        foreign key (savedAds_id) 
        references advertisement;

    alter table user_advertisement 
        add constraint FKDEE8909164DDF1F3 
        foreign key (user_id) 
        references user;

    alter table valuesetentry 
        add constraint FK247249C164F6DFF3 
        foreign key (valueSet_id) 
        references valueset;        

        
        insert into user (id, username, password, firstlogin) values (1, 'aacs', 'aacs', 1);

insert into valueset (id, name) values (1, 'remuneration');
insert into valueset (id, name) values (2, 'help_category');
insert into valuesetentry (id, bkey, valueSet_id) values (1, 'Fix', 1);
insert into valuesetentry (id, bkey, valueSet_id) values (2, 'Óradíj', 1);
insert into valuesetentry (id, bkey, valueSet_id) values (3, 'Egyik', 2);
insert into valuesetentry (id, bkey, valueSet_id) values (4, 'Másik', 2);
insert into settlement (id, zip, settlement) values (1, 3016, 'Boldog');

insert into jobcategory (id, main, name, main_id) values (1, 1, 'main1', null);
insert into jobcategory (id, main, name, main_id) values (2, 0, 'sub1', 1);
insert into jobcategory (id, main, name, main_id) values (3, 0, 'sub2', 1);
