      create table advertisement (
        id bigint generated by default as identity unique,
        other varchar(255),
        dateCreated timestamp not null,
        description varchar(2000) not null,
        homeJob boolean not null,
        maxOffer integer not null check (maxOffer>=1),
        remuneration varchar(255) not null,
        settlement_id bigint,
        category_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table conversation (
        id bigint generated by default as identity unique,
        advertisement_id bigint,
        user1_id bigint not null,
        user2_id bigint not null,
        primary key (id)
    );

    create table help (
        id bigint generated by default as identity unique,
        category varchar(255) not null,
        message varchar(255) not null,
        subject varchar(255) not null,
        user_id bigint,
        primary key (id)
    );

    create table jobcategory (
        id bigint generated by default as identity unique,
        main boolean not null,
        name varchar(255),
        main_id bigint,
        primary key (id)
    );

    create table message (
        id bigint generated by default as identity unique,
        dateCreated timestamp not null,
        text varchar(255) not null,
        conversation_id bigint not null,
        recipient_id bigint not null,
        sender_id bigint not null,
        primary key (id)
    );

    create table offer (
        id bigint generated by default as identity unique,
        amount decimal(19,2) not null,
        advertisement_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table rating (
        id bigint generated by default as identity unique,
        value double not null,
        ratedUser_id bigint,
        raterUser_id bigint not null,
        skill_id bigint not null,
        primary key (id)
    );

    create table settlement (
        id bigint generated by default as identity unique,
        settlement varchar(255),
        zipcode integer,
        primary key (id)
    );

    create table skill (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        question varchar(255) not null,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity unique,
        other varchar(255),
        firstLogin boolean not null,
        lastLogin timestamp,
        password varchar(255) not null,
        active boolean not null,
        addressCard varchar(255),
        email varchar(255),
        firstName varchar(255),
        idCard varchar(255),
        introduction varchar(255),
        lastName varchar(255),
        phoneNumber varchar(255),
        registrationDate timestamp,
        username varchar(255) not null,
        settlement_id bigint,
        primary key (id)
    );

    create table user_advertisement (
        user_id bigint not null,
        savedAds_id bigint not null,
        primary key (user_id, savedAds_id),
        unique (savedAds_id)
    );

    create table valueset (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table valuesetentry (
        id bigint generated by default as identity unique,
        bkey varchar(255) not null,
        valueSet_id bigint not null,
        primary key (id)
    );

    create table valuestore (
        id bigint generated by default as identity unique,
        name varchar(255) not null,
        value varchar(255) not null,
        primary key (id)
    );

    alter table advertisement 
        add constraint FKF85DD20564DDF1F3 
        foreign key (user_id) 
        references user;

    alter table advertisement 
        add constraint FKF85DD2055F105C76 
        foreign key (category_id) 
        references jobcategory;

    alter table advertisement 
        add constraint FKF85DD20582240ED3 
        foreign key (settlement_id) 
        references settlement;

    alter table conversation 
        add constraint FK2C1DDC835DB0CA18 
        foreign key (user1_id) 
        references user;

    alter table conversation 
        add constraint FK2C1DDC8392AACC79 
        foreign key (advertisement_id) 
        references advertisement;

    alter table conversation 
        add constraint FK2C1DDC835DB13E77 
        foreign key (user2_id) 
        references user;

    alter table help 
        add constraint FK30CF4164DDF1F3 
        foreign key (user_id) 
        references user;

    alter table jobcategory 
        add constraint FK57BF4BBB34F015DB 
        foreign key (main_id) 
        references jobcategory;

    alter table message 
        add constraint FK38EB00079AED040B 
        foreign key (conversation_id) 
        references conversation;

    alter table message 
        add constraint FK38EB00076F8E3349 
        foreign key (sender_id) 
        references user;

    alter table message 
        add constraint FK38EB0007B90120E5 
        foreign key (recipient_id) 
        references user;

    alter table offer 
        add constraint FK64C1A5C64DDF1F3 
        foreign key (user_id) 
        references user;

    alter table offer 
        add constraint FK64C1A5C92AACC79 
        foreign key (advertisement_id) 
        references advertisement;

    alter table rating 
        add constraint FKC815B19DC650EF21 
        foreign key (skill_id) 
        references skill;

    alter table rating 
        add constraint FKC815B19DAF2E5A21 
        foreign key (raterUser_id) 
        references user;

    alter table rating 
        add constraint FKC815B19DDDE5EF 
        foreign key (ratedUser_id) 
        references user;

    alter table user 
        add constraint FK36EBCB82240ED3 
        foreign key (settlement_id) 
        references settlement;

    alter table user_advertisement 
        add constraint FKDEE89091FFCC4F35 
        foreign key (savedAds_id) 
        references advertisement;

    alter table user_advertisement 
        add constraint FKDEE8909164DDF1F3 
        foreign key (user_id) 
        references user;

    alter table valuesetentry 
        add constraint FK247249C164F6DFF3 
        foreign key (valueSet_id) 
        references valueset;
        
        
        
        
        
        
        
        insert into skill(id, name, question) values (1, 'skill1', 'question1');
        insert into skill(id, name, question) values (2, 'skill2', 'question2');
        insert into skill(id, name, question) values (3, 'skill3', 'question3');
        insert into skill(id, name, question) values (4, 'skill4', 'question4');
        insert into skill(id, name, question) values (5, 'skill5', 'question5');
        insert into skill(id, name, question) values (6, 'skill6', 'question6');
        insert into user (id, username, password, firstlogin, active) values (1, 'aacs', 'aacs', 1, 1);

insert into valueset (id, name) values (1, 'remuneration');
insert into valueset (id, name) values (2, 'help_category');
insert into valuesetentry (id, bkey, valueSet_id) values (1, 'Fix', 1);
insert into valuesetentry (id, bkey, valueSet_id) values (2, 'Óradíj', 1);
insert into valuesetentry (id, bkey, valueSet_id) values (3, 'Egyik', 2);
insert into valuesetentry (id, bkey, valueSet_id) values (4, 'Másik', 2);
insert into settlement (id, zipcode, settlement) values (1, 3016, 'Boldog');

insert into jobcategory (id, main, name, main_id) values (1, 1, 'main1', null);
insert into jobcategory (id, main, name, main_id) values (2, 0, 'sub1', 1);
insert into jobcategory (id, main, name, main_id) values (3, 0, 'sub2', 1);
